language: php

php:
    - 5.4
    - 5.5
    - 5.6

sudo: false

env:
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*@dev
    - SYMFONY_VERSION=dev-master

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_install:
    - composer require symfony/symfony:${SYMFONY_VERSION} -n --prefer-source

script:
    - bin/phpspec run -f pretty
    - bin/behat -fprogress
